import type { Metadata } from 'next'
import Link from 'next/link'
import { PageHero } from '@/components/PageHero'
import { ScrollReveal } from '@/components/ScrollReveal'

export const metadata: Metadata = { title: 'About Kenvision Techniks', description: 'Meet Kenvision Techniks: trusted security, technology and professional training expertise since 2004.', alternates: { canonical: '/about' } }
const timeline = [['2004','Kenvision Techniks founded in Nairobi — first CCTV installation for a regional bank.'],['2007','Formally incorporated. Reg. No. C.140996. Expanded into information management and technology services.'],['2010','Extended to Uganda — Parliamentary complex, Bank of Uganda.'],['2014','Launched Kenvision Techniks Talent Centre. First cohort: CCTV course, 12 trainees.'],['2018','Reached 5-country footprint. Malawi (Reserve Bank, US Embassy Lilongwe), South Sudan, Namibia.'],['2022','Added ECU Remapping, Fibre Optic, GIS and geospatial solutions to the portfolio.'],['2024','20 years in service. 100+ institutional accounts. 13 active training programmes.']]
const values = [['Established expertise', 'Two decades of on-the-ground experience building infrastructure and growing skilled professionals.'], ['Practical over theoretical', 'We don’t train for certificates. We train for the field. Every course has a majority practical component.'], ['Small classes, high accountability', 'Caps of 5–18 trainees. The trainer knows your name and your work. No lecture-hall anonymity.'], ['African, professional, human', 'We understand Kenyan and East African institutional environments. Our clients are not an afterthought.']]

export default function AboutPage() { return <>
  <PageHero eyebrow="About Kenvision" title={<>Established expertise.<br />Modern technology.</>} description="Kenvision Techniks Ltd — Nairobi-based security integrator, information management specialist, and professional training academy. Founded 2004, incorporated 2007." tone="green" image="https://images.unsplash.com/photo-1531482615713-2afd69097998?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&w=800&h=520&q=85" secondaryImage="https://images.unsplash.com/photo-1497366216548-37526070297c?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&w=800&h=340&q=85"><Link className="btn-primary" href="/talent">Explore Training →</Link><Link className="btn-ghost-white" href="/contact">Get in touch</Link></PageHero>
  <section className="section section--white"><div className="container split-grid about-vision"><div><div className="eyebrow"><span />Our Vision</div><h2>Powering the African tech renaissance.</h2><p>Our vision is a continent where people doing the technical work — installing the cameras, splicing the fibre, managing the records, analysing the spatial data — are local, trained, and excellent.</p><p>That’s why Kenvision runs multiple practices under one roof: the infrastructure teams that commission real systems, and the Talent Centre that ensures the next generation knows what they’re doing.</p><Link className="btn-primary" href="/talent">Explore our training →</Link></div><div className="about-vision__image img-hover"><img src="https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=640&h=500&fit=crop&auto=format&q=85" alt="Workshop training" /></div></div></section>
  <section className="section section--sand about-history"><div className="container"><div className="eyebrow"><span />Our History</div><h2>Twenty years, by the numbers.</h2><div className="timeline">{timeline.map(([year,event])=><article className="timeline-item" key={year}><span className="copper-num">{year}</span><p>{event}</p></article>)}</div></div></section>
  <section className="section section--white about-values"><div className="container"><div className="eyebrow"><span />What we stand for</div><h2>Four things that don’t bend.</h2><div className="about-values-grid">{values.map(([title, body]) => <ScrollReveal key={title} className="about-value-card"><h3>{title}</h3><p>{body}</p></ScrollReveal>)}</div></div></section>
  <section className="final-cta about-cta"><div className="final-cta__inner"><h2>Ready to work together?</h2><p>Security infrastructure or professional training — same team, same commitment.</p><div className="inline-actions inline-actions--center"><Link className="btn-copper" href="/contact">Contact us →</Link><Link className="btn-ghost-white" href="/talent">Browse courses</Link></div></div></section>
</> }
