import type { Metadata } from 'next'
import Link from 'next/link'
import { PageHero } from '@/components/PageHero'
import { ScrollReveal } from '@/components/ScrollReveal'

export const metadata: Metadata = { title: 'About Kenvision Techniks', description: 'Meet Kenvision Techniks: trusted security, technology and professional training expertise since 2004.', alternates: { canonical: '/about' } }
const timeline = [['2004','Kenvision Techniks founded in Nairobi, beginning with a CCTV installation for a regional bank.'],['2007','Formally incorporated (Reg. No. C.140996) and expanded into information management and technology services.'],['2010','Extended into Uganda, including work for the Parliamentary complex and Bank of Uganda.'],['2014','Launched the Kenvision Techniks Talent Centre; the first CCTV cohort trained 12 participants.'],['2018','Built a five-country footprint across East and Southern Africa.'],['2022','Added ECU remapping, fibre optic, GIS and geospatial solutions to the portfolio.'],['2024','Marked 20 years in service, with 100+ institutional accounts and a growing training portfolio.']]
const values = [['Established expertise', 'Two decades of on-the-ground experience building infrastructure and growing skilled professionals.'], ['Practical over theoretical', 'We train for the field. Every course has a strong practical component grounded in real professional environments.'], ['Small classes, high accountability', 'Groups of 5–18 participants make room for practical coaching and individual attention.'], ['African, professional, human', 'We understand Kenyan and East African institutional environments. Our clients are not an afterthought.']]

export default function AboutPage() { return <>
  <PageHero eyebrow="About Kenvision" title="Established expertise. Modern technology." description="Kenvision Techniks Ltd is a Nairobi-based security integrator, information management specialist and professional training academy. Founded in 2004 and formally incorporated in 2007." tone="green" image="https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=85"><Link className="btn-copper" href="/training">Explore training <span>→</span></Link><Link className="btn-ghost-white" href="/contact">Get in touch</Link></PageHero>
  <section className="section section--white"><div className="container split-grid"><div><div className="eyebrow"><span />Our vision</div><h2>Powering the African tech renaissance.</h2><p className="section-lede">Our vision is a continent where people doing the technical work—installing cameras, splicing fibre, managing records and analysing spatial data—are local, trained and excellent.</p><p className="section-lede">That’s why Kenvision brings infrastructure teams and a professional Talent Centre together under one roof.</p><Link className="btn-primary" href="/training">Explore our training →</Link></div><div className="stat-grid"><div className="stat-card"><strong>2004</strong><b>Founded in Nairobi</b><span>More than two decades of experience</span></div><div className="stat-card"><strong>5</strong><b>Countries</b><span>East & Southern Africa</span></div><div className="stat-card"><strong>100+</strong><b>Institutional accounts</b><span>Trusted across sectors</span></div><div className="stat-card"><strong>5–18</strong><b>Small class sizes</b><span>Focused practical coaching</span></div></div></div></section>
  <section className="section section--sand"><div className="container"><div className="eyebrow"><span />Our history</div><h2>Two decades, by the numbers.</h2><div className="timeline">{timeline.map(([year,event])=><article className="timeline-item" key={year}><span className="copper-num">{year}</span><p>{event}</p></article>)}</div></div></section>
  <section className="section section--white"><div className="container"><div className="eyebrow"><span />What we stand for</div><h2>Four things that don’t bend.</h2><div className="reasons-grid">{values.map(([title, body], i) => <ScrollReveal key={title} className="reason-card"><span className="copper-num">0{i + 1}</span><h3>{title}</h3><p>{body}</p></ScrollReveal>)}</div></div></section>
  <section className="final-cta"><div className="final-cta__inner"><div className="final-cta__rule"/><h2>Let’s build capability together.</h2><p>Tell us what your organisation needs. We’ll bring the right expertise to the conversation.</p><div className="inline-actions inline-actions--center"><Link className="btn-copper" href="/contact">Contact our team <span>→</span></Link><Link className="btn-ghost-white" href="/solutions">Explore our solutions</Link></div></div></section>
</> }
