import type { Metadata } from 'next'
import { PageHero } from '@/components/PageHero'
export const metadata: Metadata = { title: 'Training Terms & Policies', description: 'Terms governing training enrolment and participation at the Kenvision Techniks Talent Centre.', alternates: { canonical: '/terms' } }
const sections = [
  ['Enrolment', 'Course places are allocated on a first-come, first-served basis. Enrolment is confirmed only when Kenvision Techniks sends written confirmation. Please wait for that confirmation before attending.'],
  ['Registration deadline', 'Participants should register at least five working days before the course start date. Late registrations may be accepted at our discretion, subject to available places.'],
  ['Standard training hours', 'Standard training hours are 8:30am to 4:00pm each training day. Hours may vary for specific courses; the schedule will be communicated in your confirmation.'],
  ['What the course fee covers', 'The course fee includes tuition, course notes, morning tea or coffee, water and lunch for each training day. Travel and accommodation are not included.'],
  ['Cancellation — more than 10 working days', 'Cancellations received more than 10 working days before the course start date are eligible for a refund, less a 20% administration fee. Refunds are processed within 14 working days.'],
  ['Cancellation — 10 working days or fewer', 'Cancellations received 10 or fewer working days before the course start date are non-refundable. The full course fee is forfeited.'],
  ['Participant substitution', 'You may substitute another participant, provided written notice is given at least three working days before the course start date. The substitute must meet any applicable prerequisites.'],
  ['Minimum enrolment policy', 'Kenvision Techniks may cancel or reschedule a course if the minimum enrolment threshold is not met. In that case, enrolled participants receive a full refund and we will provide as much notice as possible.'],
  ['Liability', 'Kenvision Techniks Ltd is not liable for indirect, incidental or consequential loss arising from attendance at, or inability to attend, a training course. Liability is limited to the course fee paid. Participants must follow all safety instructions.'],
  ['Confidentiality and photography', 'Proprietary course materials are for participant use only and may not be reproduced or distributed without written consent. Kenvision Techniks may photograph training sessions for marketing; participants who object should notify the trainer at the start of the session.'],
]
export default function TermsPage() { return <><PageHero eyebrow="Legal" title="Training terms & policies" description="These terms govern enrolment and participation at the Kenvision Techniks Talent Centre." tone="green"/><section className="section section--white"><div className="container terms-list">{sections.map(([title,content],i)=><article className="terms-row" key={title}><span className="copper-num">{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{content}</p></div></article>)}<p className="terms-contact">Kenvision Techniks Ltd · Reg. No. C.140996 · Q7–Q9 Feliz Building, Kahawa Sukari Avenue, Nairobi, Kenya<br/><a href="mailto:info@kenvisiontechniks.com">info@kenvisiontechniks.com</a> · <a href="tel:+254725579251">+254 725 579 251</a></p></div></section></> }
