import type { Metadata } from 'next'
export const metadata: Metadata = { title: 'Training Terms & Policies', description: 'Terms governing training enrolment and participation at the Kenvision Techniks Talent Centre.', alternates: { canonical: '/terms' } }
const sections = [
  ['Enrollment', 'Course places are allocated on a first-come, first-served basis. Your enrollment is confirmed only upon receipt of a written confirmation email from Kenvision Techniks. Do not attend training until you have received that email.'],
  ['Registration deadline', 'Participants must register at least 5 working days before the course start date. Late registrations may be accommodated at our discretion, subject to available places.'],
  ['Standard training hours', 'Standard training hours are 8:30am to 4:00pm each training day. Hours may vary for specific courses — the schedule will be communicated in your confirmation.'],
  ['What the course fee covers', 'The course fee includes tuition, course notes, morning tea/coffee, water, and lunch for each training day. Travel and accommodation are not included.'],
  ['Cancellation — more than 10 working days', 'Cancellations received more than 10 working days before the course start date are eligible for a refund, less a 20% administration fee. Refunds processed within 14 working days.'],
  ['Cancellation — 10 working days or fewer', 'Cancellations received 10 or fewer working days before the course start date are non-refundable. The full course fee is forfeited.'],
  ['Substitution', 'You may substitute another participant in your place, provided written notice is given at least 3 working days before the course start date. The substitute must meet any applicable prerequisites.'],
  ['Minimum enrollment policy', 'Kenvision Techniks reserves the right to cancel or reschedule a course if the minimum enrollment threshold is not met. In such cases, all enrolled participants receive a full refund. We will provide as much notice as possible.'],
  ['Liability', 'Kenvision Techniks Ltd shall not be liable for any indirect, incidental, or consequential loss arising from attendance at, or inability to attend, a training course. Our liability is limited to the course fee paid. Participants attend at their own risk and must follow all safety instructions.'],
  ['Confidentiality', 'Proprietary course materials are for participant use only and may not be reproduced or distributed without written consent. Kenvision Techniks may photograph training sessions for marketing purposes; participants who object should notify the trainer at the start of the session.'],
]
export default function TermsPage() { return <><section className="terms-hero"><div className="container"><div className="eyebrow"><span />Legal</div><h1>Terms &amp; Policies</h1><p>These terms govern training enrollment and participation at the Kenvision Techniks Talent Centre.</p></div></section><section className="section section--white"><div className="container terms-list">{sections.map(([title,content])=><article className="terms-row" key={title}><h2>{title}</h2><p>{content}</p></article>)}<p className="terms-contact">Kenvision Techniks Ltd · Reg. No. C.140996 · Q7–Q9 Feliz Building, Kahawa Sukari Avenue, Nairobi, Kenya<br/><a href="mailto:info@kenvisiontechniks.com">info@kenvisiontechniks.com</a> · <a href="tel:+254725579251">+254 725 579 251</a></p></div></section></> }
